extends Node

var UPGRADE_EMPTY_0 = tr("UPGRADE_EMPTY_0.")

var UPGRADE_EXTRA_LIFE = tr("UPGRADE_EXTRA_LIFE.")
var UPGRADE_EXTRA_LIFE_0 = tr("UPGRADE_EXTRA_LIFE_0.")
var UPGRADE_EXTRA_LIFE_1 = tr("UPGRADE_EXTRA_LIFE_1.")
var UPGRADE_EXTRA_LIFE_2 = tr("UPGRADE_EXTRA_LIFE_2.")
var UPGRADE_EXTRA_LIFE_3 = tr("UPGRADE_EXTRA_LIFE_3.")

var UPGRADE_PADDLE_SPEED = tr("UPGRADE_PADDLE_SPEED.")
var UPGRADE_PADDLE_SPEED_0 = tr("UPGRADE_PADDLE_SPEED_0.")
var UPGRADE_PADDLE_SPEED_1 = tr("UPGRADE_PADDLE_SPEED_1.")
var UPGRADE_PADDLE_SPEED_2 = tr("UPGRADE_PADDLE_SPEED_2.")
var UPGRADE_PADDLE_SPEED_3 = tr("UPGRADE_PADDLE_SPEED_3.")
