extends Node

var UPGRADE_EMPTY_0 = tr("UPGRADE_EMPTY_0.")

var UPGRADE_EXTRA_LIFE = tr("UPGRADE_EXTRA_LIFE.")
var UPGRADE_EXTRA_LIFE_0 = tr("UPGRADE_EXTRA_LIFE_0.")
var UPGRADE_EXTRA_LIFE_1 = tr("UPGRADE_EXTRA_LIFE_1.")
var UPGRADE_EXTRA_LIFE_2 = tr("UPGRADE_EXTRA_LIFE_2.")
var UPGRADE_EXTRA_LIFE_3 = tr("UPGRADE_EXTRA_LIFE_3.")

var UPGRADE_PADDLE_SPEED = tr("UPGRADE_PADDLE_SPEED.")
var UPGRADE_PADDLE_SPEED_0 = tr("UPGRADE_PADDLE_SPEED_0.")
var UPGRADE_PADDLE_SPEED_1 = tr("UPGRADE_PADDLE_SPEED_1.")
var UPGRADE_PADDLE_SPEED_2 = tr("UPGRADE_PADDLE_SPEED_2.")
var UPGRADE_PADDLE_SPEED_3 = tr("UPGRADE_PADDLE_SPEED_3.")

var UPGRADE_BOMB_RADIUS   = tr("UPGRADE_BOMB_RADIUS.")
var UPGRADE_BOMB_RADIUS_0 = tr("UPGRADE_BOMB_RADIUS_0.")
var UPGRADE_BOMB_RADIUS_1 = tr("UPGRADE_BOMB_RADIUS_1.")
var UPGRADE_BOMB_RADIUS_2 = tr("UPGRADE_BOMB_RADIUS_2.")
var UPGRADE_BOMB_RADIUS_3 = tr("UPGRADE_BOMB_RADIUS_3.")

var UPGRADE_BOMB_SCORE   = tr("UPGRADE_BOMB_SCORE.")
var UPGRADE_BOMB_SCORE_0 = tr("UPGRADE_BOMB_SCORE_0.")
var UPGRADE_BOMB_SCORE_1 = tr("UPGRADE_BOMB_SCORE_1.")
var UPGRADE_BOMB_SCORE_2 = tr("UPGRADE_BOMB_SCORE_2.")
var UPGRADE_BOMB_SCORE_3 = tr("UPGRADE_BOMB_SCORE_3.")

var UPGRADE_BOMB_POWER   = tr("UPGRADE_BOMB_POWER.")
var UPGRADE_BOMB_POWER_0 = tr("UPGRADE_BOMB_POWER_0.")
var UPGRADE_BOMB_POWER_1 = tr("UPGRADE_BOMB_POWER_1.")
var UPGRADE_BOMB_POWER_2 = tr("UPGRADE_BOMB_POWER_2.")
var UPGRADE_BOMB_POWER_3 = tr("UPGRADE_BOMB_POWER_3.")

var UPGRADE_ROCKET_COUNT   = tr("UPGRADE_ROCKET_COUNT.")
var UPGRADE_ROCKET_COUNT_0 = tr("UPGRADE_ROCKET_COUNT_0.")
var UPGRADE_ROCKET_COUNT_1 = tr("UPGRADE_ROCKET_COUNT_1.")
var UPGRADE_ROCKET_COUNT_2 = tr("UPGRADE_ROCKET_COUNT_2.")

var UPGRADE_ROCKET_SCORE   = tr("UPGRADE_ROCKET_SCORE.")
var UPGRADE_ROCKET_SCORE_0 = tr("UPGRADE_ROCKET_SCORE_0.")
var UPGRADE_ROCKET_SCORE_1 = tr("UPGRADE_ROCKET_SCORE_1.")
var UPGRADE_ROCKET_SCORE_2 = tr("UPGRADE_ROCKET_SCORE_2.")
var UPGRADE_ROCKET_SCORE_3 = tr("UPGRADE_ROCKET_SCORE_3.")

var UPGRADE_ROCKET_POWER   = tr("UPGRADE_ROCKET_POWER.")
var UPGRADE_ROCKET_POWER_0 = tr("UPGRADE_ROCKET_POWER_0.")
var UPGRADE_ROCKET_POWER_1 = tr("UPGRADE_ROCKET_POWER_1.")
var UPGRADE_ROCKET_POWER_2 = tr("UPGRADE_ROCKET_POWER_2.")
var UPGRADE_ROCKET_POWER_3 = tr("UPGRADE_ROCKET_POWER_3.")

var UI_SLOTBUY = tr("UI_SLOTBUY.")

func FUNC_UIM_BUY_SLOT_BUTTON(n: int) -> String:
    return tr_n("UIM_BUY_SLOT_BUTTON", "UIM_BUY_SLOT_BUTTON_PLURAL", n, "GUI button to buy new upgradeslot.")

func FUNC_UIM_BUY_UPGRADE_BUTTON(n: int) -> String:
    return tr_n("UIM_BUY_UPGRADE_BUTTON", "UIM_BUY_UPGRADE_BUTTON_PLURAL", n, "GUI button to buy new upgrade.")
